parameters:
    icap_website.page.class:             Icap\WebsiteBundle\Entity\WebsitePage
    icap_website.repository.page.class:  Icap\WebsiteBundle\Repository\WebsitePageRepository

services:
    icap_website.repository.page:
        class:           "%icap_website.repository.page.class%"
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - "%icap_website.page.class%"